# Generated by Django 4.2.1 on 2023-07-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
