# Generated by Django 4.2.1 on 2023-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_blog', '0006_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocontest',
            name='message',
        ),
        migrations.AddField(
            model_name='photocontest',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
